### ISSUE TITLE
1.3 Roadmap

### ISSUE THREAD

**Issue by sksamuel** [51zero/eel-sdk#267]
These are the features for a 1.3 release.

- [x] Improve JDBC #248 236
- [ ] Add support for typed rows
- [ ] eel cli
- [ ] #262 enforce schema option
- [x] #263 on complete does not fire

**Comment by garyfrost** [comment]
@sksamuel @hannesmiller do you think we should consider the Java API for the 1.3 roadmap?

**Comment by hannesmiller** [comment]
Why not - I have already started on it.

Sent from my iPhone

On 20 May 2017, at 17:16, Gary Frost <notifications@github.com<mailto:notifications@github.com>> wrote:


@sksamuel<https://github.com/sksamuel> @hannesmiller<https://github.com/hannesmiller> do you think we should consider the Java API for the 1.3 roadmap?

**Comment by sksamuel** [comment]
For 1.3 yes.

**Comment by sksamuel** [comment]
Closing this, as an epic doesn't really work on github.
